const defaultInput =[
    '# Markdown\n',
    '## Lightweight markup language\n',
    'Easy-to-read, easy-to-write plain text format that can be converted into structurally valid HTML.\n',
    '## Text Decoration\n',
    'Markdown "`_italic_`" corresponds to HTML "`<em>italic</em>`  e.g. _italic_."\n',
    'Markdown "`**bold**`" corresponds to HTML "`<strong>bold</strong>` e.g. **bold**."\n',
    'Markdown "`` `monospace` ``" corresponds to HTML "`<code>monospace</code>` e.g. `monospace`."\n',
    '## Unordered List\n',
    'Markdown',
    '```',
    '* first',
    '* second',
    '* third',
    '```\n',
    'HTML',
    '```', 
    '<ul>',
    '  <li>first</li>',
    '  <li>second</li>',
    '  <li>third</li>',
    '</ul>',
    '```\n',
    'Rendered',
    '* first',
    '* second',
    '* third',
    '\n',
    '> The overriding design goal for Markdown’s formatting syntax is to make it as readable as possible.\n',
    '![Markdown logo](https://goo.gl/dsTqVr "Markdown logo")\n',
    '[Read more on Wikipedia](https://en.wikipedia.org/wiki/Markdown)'
].join('\n')

export default defaultInput
